### ISSUE TITLE
编译失败，提示Manifest merger failed

### ISSUE THREAD

**Issue by c1024** [550609334/Twobbble#1]
下载下来编译失败，提示
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute activity#com.tencent.bugly.beta.ui.BetaActivity@theme value=(@style/DialogActivityTheme) from AndroidManifest.xml:64:13-55
  	is also present at [com.tencent.bugly:crashreport_upgrade:1.3.1] AndroidManifest.xml:25:13-61 value=(@android:style/Theme.Translucent).
  	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:62:9-65:15 to override.

**Comment by liuzipengWally** [comment]
这是bugly新版导致，已更新代码 去掉了这个style的引用

**Comment by 550609334** [comment]
这是bugly新版导致，已更新代码 去掉了这个style的引用
